altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  255a3138-034d-4b27-93f9-eb8e5666ac27:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-02T14:11:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c166386c-402d-4096-bd62-0f4b57c0510f
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 43dfea79-c4db-48c4-8701-5510a3db466b
        userCondition: null
fs: icons
handle: icons
name: Iconen
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: icons
transformSubpath: transforms
