columnSuffix: null
handle: fieldEmail
instructions: null
name: Email
searchable: false
settings:
  advancedFields:
    - target
  fullGraphqlData: true
  maxLength: 255
  showLabelField: true
  types:
    - email
translationKeyFormat: null
translationMethod: language
type: craft\fields\Link
