defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9045a806-e324-483e-97f4-5870dd25140e # Diensten
handle: diensten
maxAuthors: 1
name: Diensten
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  c3ffcf57-ea2c-4a07-a6bd-3768cfb8b05d: # [NL] Boilerplate
    enabledByDefault: true
    hasUrls: true
    template: diensten/index
    uriFormat: diensten
type: single
