handle: formieSubscribe
name: 'Subscribe template'
outputCssLayout: true
outputCssLocation: page-header
outputCssTheme: true
outputJsBase: true
outputJsLocation: page-footer
outputJsTheme: true
sortOrder: 3
template: _formie/formieSubscribe
useCustomTemplates: true
